/**
 * Urdu names for LEHAR's 107 districts, for the home hero's district picker.
 *
 * The backend only knows districts by their English name (backend/ml/
 * districts.py), which stays the key everywhere, in URLs and API calls. These
 * are the common Urdu spellings, for display only; a unit test checks the
 * table covers exactly the backend's list, so a new district cannot silently
 * go without one.
 */
export const DISTRICT_NAME_UR: Record<string, string> = {
  // Punjab
  Lahore: "لاہور",
  Faisalabad: "فیصل آباد",
  Rawalpindi: "راولپنڈی",
  Gujranwala: "گوجرانوالہ",
  Multan: "ملتان",
  Sargodha: "سرگودھا",
  Sialkot: "سیالکوٹ",
  Bahawalpur: "بہاولپور",
  Bahawalnagar: "بہاولنگر",
  "Rahim Yar Khan": "رحیم یار خان",
  "Dera Ghazi Khan": "ڈیرہ غازی خان",
  Muzaffargarh: "مظفر گڑھ",
  Jhang: "جھنگ",
  Sahiwal: "ساہیوال",
  Okara: "اوکاڑہ",
  Kasur: "قصور",
  Vehari: "وہاڑی",
  Sheikhupura: "شیخوپورہ",
  Attock: "اٹک",
  Mianwali: "میانوالی",
  Bhakkar: "بھکر",
  Layyah: "لیہ",
  Rajanpur: "راجن پور",
  Khanewal: "خانیوال",
  Lodhran: "لودھراں",
  "Toba Tek Singh": "ٹوبہ ٹیک سنگھ",
  Chiniot: "چنیوٹ",
  Hafizabad: "حافظ آباد",
  "Mandi Bahauddin": "منڈی بہاؤالدین",
  Gujrat: "گجرات",
  Jhelum: "جہلم",
  Chakwal: "چکوال",
  Pakpattan: "پاکپتن",
  "Nankana Sahib": "ننکانہ صاحب",
  // Sindh
  Karachi: "کراچی",
  Hyderabad: "حیدرآباد",
  Sukkur: "سکھر",
  Larkana: "لاڑکانہ",
  "Shaheed Benazirabad": "شہید بینظیر آباد",
  Mirpurkhas: "میرپور خاص",
  Khairpur: "خیرپور",
  Dadu: "دادو",
  Badin: "بدین",
  Thatta: "ٹھٹہ",
  Jacobabad: "جیکب آباد",
  Kashmore: "کشمور",
  Shikarpur: "شکارپور",
  Ghotki: "گھوٹکی",
  Sanghar: "سانگھڑ",
  Jamshoro: "جامشورو",
  "Naushahro Feroze": "نوشہرو فیروز",
  Matiari: "مٹیاری",
  "Tando Allahyar": "ٹنڈو الہ یار",
  "Tando Muhammad Khan": "ٹنڈو محمد خان",
  "Qambar Shahdadkot": "قمبر شہدادکوٹ",
  Sujawal: "سجاول",
  Tharparkar: "تھرپارکر",
  Umerkot: "عمرکوٹ",
  // Khyber Pakhtunkhwa
  Peshawar: "پشاور",
  Mardan: "مردان",
  Swat: "سوات",
  Abbottabad: "ایبٹ آباد",
  "Dera Ismail Khan": "ڈیرہ اسماعیل خان",
  Charsadda: "چارسدہ",
  Nowshera: "نوشہرہ",
  Bannu: "بنوں",
  Swabi: "صوابی",
  Kohat: "کوہاٹ",
  Karak: "کرک",
  Hangu: "ہنگو",
  "Lakki Marwat": "لکی مروت",
  Tank: "ٹانک",
  "Dir Lower": "لوئر دیر",
  "Dir Upper": "اپر دیر",
  Chitral: "چترال",
  Buner: "بونیر",
  Shangla: "شانگلہ",
  Malakand: "مالاکنڈ",
  Haripur: "ہری پور",
  Mansehra: "مانسہرہ",
  Battagram: "بٹگرام",
  Kohistan: "کوہستان",
  Bajaur: "باجوڑ",
  Khyber: "خیبر",
  Kurram: "کرم",
  Orakzai: "اورکزئی",
  Mohmand: "مہمند",
  "North Waziristan": "شمالی وزیرستان",
  "South Waziristan": "جنوبی وزیرستان",
  // Balochistan
  Quetta: "کوئٹہ",
  Khuzdar: "خضدار",
  Sibi: "سبی",
  Nasirabad: "نصیر آباد",
  Kech: "کیچ",
  Gwadar: "گوادر",
  Lasbela: "لسبیلہ",
  Jaffarabad: "جعفر آباد",
  Zhob: "ژوب",
  Loralai: "لورالائی",
  Panjgur: "پنجگور",
  Chagai: "چاغی",
  // Capital / AJK / GB
  Islamabad: "اسلام آباد",
  Muzaffarabad: "مظفرآباد",
  Gilgit: "گلگت",
  Mirpur: "میرپور",
  Kotli: "کوٹلی",
  Skardu: "سکردو",
};

/** The Urdu name, or null for a district the table does not know (yet). */
export function districtNameUr(district: string): string | null {
  return DISTRICT_NAME_UR[district] ?? null;
}
