"""add alert engine tables (LEHAR Phase 2)

Adds the four alert tables (alerts, alert_subscriptions, alert_deliveries,
alert_runs) and the additive fields.irrigation_threshold_mm column.

Written by hand rather than autogenerated so the SQLite path works too:
op.add_column on SQLite is fine for a NULLABLE column with no default,
which is exactly what irrigation_threshold_mm is — so the same migration
upgrades both the local SQLite database and Postgres/Neon.

Revision ID: b7f3a9c15e42
Revises: c83b98abe752
Create Date: 2026-09-24

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7f3a9c15e42'
down_revision: Union[str, Sequence[str], None] = 'c83b98abe752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('district_code', sa.String(length=64), nullable=False),
        sa.Column('type', sa.String(length=32), nullable=False),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('title_en', sa.String(length=200), nullable=False),
        sa.Column('title_ur', sa.String(length=200), nullable=False),
        sa.Column('body_en', sa.Text(), nullable=False),
        sa.Column('body_ur', sa.Text(), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('dedupe_key', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alerts_district_code'), 'alerts', ['district_code'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    # UNIQUE: the database itself enforces dedupe (district+type+level+day),
    # so two concurrent runs can never both raise the same alert.
    op.create_index(op.f('ix_alerts_dedupe_key'), 'alerts', ['dedupe_key'], unique=True)

    op.create_table(
        'alert_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(length=16), nullable=False),
        sa.Column('target', sa.String(length=255), nullable=False),
        sa.Column('districts', sa.JSON(), nullable=True),
        sa.Column('min_level', sa.Integer(), nullable=False),
        sa.Column('language', sa.String(length=2), nullable=False),
        sa.Column('verified', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alert_subscriptions_channel'), 'alert_subscriptions', ['channel'], unique=False)

    op.create_table(
        'alert_deliveries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('alert_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=True),
        sa.Column('channel', sa.String(length=16), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error', sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
        sa.ForeignKeyConstraint(['subscription_id'], ['alert_subscriptions.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_index(
        op.f('ix_alert_deliveries_subscription_id'), 'alert_deliveries', ['subscription_id'], unique=False
    )
    op.create_index(op.f('ix_alert_deliveries_channel'), 'alert_deliveries', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_status'), 'alert_deliveries', ['status'], unique=False)

    op.create_table(
        'alert_runs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('districts_checked', sa.Integer(), nullable=False),
        sa.Column('alerts_raised', sa.Integer(), nullable=False),
        sa.Column('alerts_suppressed', sa.Integer(), nullable=False),
        sa.Column('alerts_resolved', sa.Integer(), nullable=False),
        sa.Column('trigger', sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alert_runs_started_at'), 'alert_runs', ['started_at'], unique=False)

    # Nullable, no server default: safe on SQLite and instant on Postgres.
    # NULL means "use ALERT_IRRIGATION_THRESHOLD_MM", which is exactly what
    # every pre-Phase-2 row should mean.
    op.add_column('fields', sa.Column('irrigation_threshold_mm', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('fields', 'irrigation_threshold_mm')

    op.drop_index(op.f('ix_alert_runs_started_at'), table_name='alert_runs')
    op.drop_table('alert_runs')

    op.drop_index(op.f('ix_alert_deliveries_status'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_channel'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_subscription_id'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')

    op.drop_index(op.f('ix_alert_subscriptions_channel'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')

    op.drop_index(op.f('ix_alerts_dedupe_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_district_code'), table_name='alerts')
    op.drop_table('alerts')
