"""add actual_observations table

Revision ID: c83b98abe752
Revises: 1d4cce831121
Create Date: 2026-08-14 03:21:48.838975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83b98abe752'
down_revision: Union[str, Sequence[str], None] = '1d4cce831121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_log_id', sa.Integer(), nullable=False),
    sa.Column('actual_irrigation_mm', sa.Float(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['prediction_log_id'], ['prediction_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actual_observations_prediction_log_id'), 'actual_observations', ['prediction_log_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actual_observations_prediction_log_id'), table_name='actual_observations')
    op.drop_table('actual_observations')
    # ### end Alembic commands ###
